name: Update Harga LM Harian

on:
  schedule:
    - cron: "35 1 * * *"  # 08:35 WIB (UTC+7)
  workflow_dispatch:

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch harga 1g dari LogamMulia
        run: |
          node scripts/fetch-lm.js

      - name: Commit & push perubahan data
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/prices.json
            git commit -m "chore(data): update harga 1g harian"
            git push
          else
            echo "Tidak ada perubahan data."
          fi
